#!/usr/bin/env bash
#set -euo pipefail

set -e

INSTALL_DIR=/sphenix/user/mitrankov/novel/coresoftware_TrackingDiagnostics/install

export LD_LIBRARY_PATH="${INSTALL_DIR}/lib:${LD_LIBRARY_PATH:-}"
export ROOT_INCLUDE_PATH="${INSTALL_DIR}/include:${ROOT_INCLUDE_PATH:-}"

echo "LD_LIBRARY_PATH=${LD_LIBRARY_PATH}"
echo "ROOT_INCLUDE_PATH=${ROOT_INCLUDE_PATH}"

usage() {
  cat <<'USAGE'
Usage:
  run_tpc_v0_job.sh CONFIG_FILE INPUT_LIST OUTPUT_FILE [NEVENTS] [SKIP]

CONFIG_FILE is a shell file generated by submit_tpc_v0.sh.
The environment must already contain the sPHENIX setup and the installed
TrackingDiagnostics library, or set V0_SETUP_SCRIPT in CONFIG_FILE.
USAGE
}

[[ $# -ge 3 ]] || { usage; exit 2; }

CONFIG_FILE=$(readlink -f "$1")
INPUT_LIST=$(readlink -f "$2")
OUTPUT_FILE="$3"
NEVENTS=${4:-0}
SKIP=${5:-0}

# shellcheck disable=SC1090
source "$CONFIG_FILE"

if [[ -n "${V0_SETUP_SCRIPT:-}" ]]; then
  # shellcheck disable=SC1090
  source "$V0_SETUP_SCRIPT"
fi

MACRO=${V0_MACRO:?V0_MACRO is not set in the config file}
mkdir -p "$(dirname "$OUTPUT_FILE")"

root -l -b -q \
  "${MACRO}(\"${INPUT_LIST}\",\"${OUTPUT_FILE}\",${NEVENTS},${SKIP})"
